"""init

Revision ID: 02caabd1ae57
Revises: 
Create Date: 2026-10-04 20:23:38.433345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '02caabd1ae57'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('spicies', sa.Enum('DOG', 'CAT', 'BIRD', 'RODENT', 'REPTILE', 'OTHER', name='spicies'), nullable=True))
    op.drop_column('pets', 'spices')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('spices', postgresql.ENUM('DOG', 'CAT', 'BIRD', 'RODENT', 'REPTILE', 'OTHER', name='spicies'), autoincrement=False, nullable=False))
    op.drop_column('pets', 'spicies')
    # ### end Alembic commands ###
